language: node_js
node_js:
  - "stable"
install:
  - npm install
services:
  - redis-server
  - mysql
  - elasticsearch
before_install:
  - export DATABASE_URL="mysql://root:@127.0.0.1/nozama"
  - export NPM_CONFIG_PRODUCTION=false
  - mysql -e 'CREATE DATABASE IF NOT EXISTS nozama;'
  - mysql -u root --default-character-set=utf8 nozama < database/users.sql
  - mysql -u root --default-character-set=utf8 nozama < products/database/product_reviews.sql
  before_script:
  - sleep 10