CREATE TABLE `product_analytics`(
 `id` INTEGER NOT NULL AUTO_INCREMENT,
 `user_id` INTEGER NOT NULL,
 `activity` VARCHAR(20) NOT NULL,
 `details` JSON DEFAULT NULL,
 `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `duration` INTEGER NULL,
 PRIMARY KEY(`id`)
);
